# Generated by Django 4.1 on 2022-08-18 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
