# Generated by Django 4.1 on 2022-08-18 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_persona_created"),
    ]

    operations = [
        migrations.RemoveField(model_name="persona", name="created",),
        migrations.AddField(
            model_name="persona",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, editable=False, null=True
            ),
        ),
    ]
